# ukol-10: Zaměstnanci a Projekty

# Zaměstnanci
Uvažuj, že zpracováváš analýzu pro softwarovou firmu. Firma má kanceláře v Praze, Plzni a Liberci. Seznam zaměstnanců pro jednotlivé kanceláře najdeš v souborech zam_praha.csv, zam_plzeň.csv a zam_liberec.csv.

import requests

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_praha.csv")
open("zam_praha.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_plzeň.csv")
open("zam_plzeň.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_liberec.csv")
open("zam_liberec.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/platy_2021_02.csv")
open("platy_2021_02.csv", "wb").write(r.content)

Načti data o zaměstnancích z CSV souborů do tabulek (DataFrame). Ke každé tabulce přidej nový sloupec mesto, které bude obsahovat informaci o tom, ve kterém městě zaměstnanec pracuje.
Vytvoř novou tabulku zamestnanci a ulož do ní informace o všech zaměstnancích.

Ze souboru platy_2021_02.csv načti platy zaměstnanců za únor 2021. Propoj tabulku (operace join) s platy a tabulku se zaměstnanci pomocí sloupce cislo_zamestnance.

Porovnej rozměry tabulek před spojením a po spojení. Pokud nemá některý zaměstnanec plat za únor, znamená to, že v naší firmě již nepracuje.

Spočti průměrný plat zaměstnanců v jednotlivých kancelářích.

### Dobrovolný doplněk

Ulož do proměnné počet zaměstnaců, kteří v naší firmě již nepracují.

V rámci úspory se IT oddělení rozhodlo prověřit licence přidělené zaměstnancům, kteří ve firmě již nepracují. Vytvoř samostatnou tabulku, která obsahuje jména zaměstnanců, kteří ve firmě již nepracují. Tabulku ulož do souboru CSV.

In [3]:
# Načti data o zaměstnancích z CSV souborů do tabulek (DataFrame). 

import requests

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_praha.csv")
open("ukol-10_zam_praha.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_plzeň.csv")
open("ukol-10_zam_plzeň.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/zam_liberec.csv")
open("ukol-10_zam_liberec.csv", "wb").write(r.content)

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/platy_2021_02.csv")
open("ukol-10_platy_2021_02.csv", "wb").write(r.content)


import pandas

zam_praha = pandas.read_csv("ukol-10_zam_praha.csv") 
zam_plzen = pandas.read_csv("ukol-10_zam_plzeň.csv") 
zam_liberec = pandas.read_csv("ukol-10_zam_liberec.csv") 
platy = pandas.read_csv("ukol-10_platy_2021_02.csv")

          jmeno  prijimeni   telefonni_cislo  cislo_zamestnance
0         Brian       Hall  +421 949 656 098                 30
1         Marta   Kolářová       730 456 163                 32
2          John    Moravec       725 092 179                 33
3      Dominika    Kopecká       722 747 626                 34
4        Marcel      Hájek  +421 902 928 669                 35
5        Milada  Hernandez       773 373 704                 38
6     Catherine     Bender       604 068 460                 40
7          Olga    Němcová  +421 914 172 243                 41
8       Jeffrey    Šťastný       607 628 821                 44
9        Kamila     Říhová  +421 948 396 069                 47
10      Jaromír     Miller  +421 912 615 902                 49
11  Christopher      Zeman  +421 948 150 084                 51
12     Karolína      Short       721 589 083                 53
13     Michelle    Vlčková  +421 41 720 7806                 54
14      Jeffrey   Pospíšil  +421 55 491 6940                 56
15     Ladislav     Blažek  +421 910 274 975                 57
16         John     Bailey       775 021 116                 58
17      William    Shelton  +421 47 745 8219                 60
18    Miroslava     Veselá       774 029 254                 62
19      William  Alexander  +421 949 106 724                 63
20     Kimberly       Bass  +421 912 169 840                 64
21       Nathan    Svoboda       728 710 923                 66
22        Luděk     Bartoš  +421 940 700 326                 69
23       Dillon      Black       734 300 978                 70
24       Robert       Říha       727 351 984                 72
25        Steve      Šimek       604 966 101                 74
26      Theresa   Kučerová  +421 48 528 0081                 76
27        Marta     Butler  +421 944 196 827                 78
28     Samantha  Kadlecová  +421 904 841 543                 80

In [7]:
# Ke každé tabulce přidej nový sloupec mesto, které bude obsahovat informaci o tom, ve kterém městě zaměstnanec pracuje.

zam_praha["mesto"] = "Praha"
zam_plzen["mesto"] = "Plzeň"
zam_liberec["mesto"] = "Liberec"

          jmeno  prijimeni   telefonni_cislo  cislo_zamestnance  mesto
0         Brian       Hall  +421 949 656 098                 30  Praha
1         Marta   Kolářová       730 456 163                 32  Praha
2          John    Moravec       725 092 179                 33  Praha
3      Dominika    Kopecká       722 747 626                 34  Praha
4        Marcel      Hájek  +421 902 928 669                 35  Praha
5        Milada  Hernandez       773 373 704                 38  Praha
6     Catherine     Bender       604 068 460                 40  Praha
7          Olga    Němcová  +421 914 172 243                 41  Praha
8       Jeffrey    Šťastný       607 628 821                 44  Praha
9        Kamila     Říhová  +421 948 396 069                 47  Praha
10      Jaromír     Miller  +421 912 615 902                 49  Praha
11  Christopher      Zeman  +421 948 150 084                 51  Praha
12     Karolína      Short       721 589 083                 53  Praha
13     Michelle    Vlčková  +421 41 720 7806                 54  Praha
14      Jeffrey   Pospíšil  +421 55 491 6940                 56  Praha
15     Ladislav     Blažek  +421 910 274 975                 57  Praha
16         John     Bailey       775 021 116                 58  Praha
17      William    Shelton  +421 47 745 8219                 60  Praha
18    Miroslava     Veselá       774 029 254                 62  Praha
19      William  Alexander  +421 949 106 724                 63  Praha
20     Kimberly       Bass  +421 912 169 840                 64  Praha
21       Nathan    Svoboda       728 710 923                 66  Praha
22        Luděk     Bartoš  +421 940 700 326                 69  Praha
23       Dillon      Black       734 300 978                 70  Praha
24       Robert       Říha       727 351 984                 72  Praha
25        Steve      Šimek       604 966 101                 74  Praha
26      Theresa   Kučerová  +421 48 528 0081                 76  Praha
27        Marta     Butler  +421 944 196 827                 78  Praha
28     Samantha  Kadlecová  +421 904 841 543                 80  Praha

In [10]:
# zam_praha
# zam_plzen
zam_liberec

        jmeno    prijimeni   telefonni_cislo  cislo_zamestnance    mesto
0        Nela      Šťastná       728 454 176                 83  Liberec
1     Heather      Marková       604 404 522                 84  Liberec
2      Krista  Procházková  +421 50 444 5544                 85  Liberec
3    Jennifer        Brown       775 545 190                 86  Liberec
4   Ladislava    Blackwell  +421 913 487 200                 87  Liberec
5      Robert       Macias  +421 49 929 6856                 88  Liberec
6        Dana        Reyes  +421 904 153 942                 90  Liberec
7       Vasyl       Veselý       603 759 413                 92  Liberec
8       Randy       Veselý       777 149 125                 95  Liberec
9      Audrey        Allen  +421 908 839 506                 96  Liberec
10       Ivan       Bartoš       603 226 051                 99  Liberec

In [14]:
#  Vytvoř novou tabulku zamestnanci a ulož do ní informace o všech zaměstnancích.
# vytvořila jsem si nový index pro novou tabulku (ignore index), aby byl 0-n

zamci = pandas.concat([zam_praha,zam_plzen,zam_liberec], ignore_index = True)
zamci

          jmeno    prijimeni   telefonni_cislo  cislo_zamestnance    mesto
0         Brian         Hall  +421 949 656 098                 30    Praha
1         Marta     Kolářová       730 456 163                 32    Praha
2          John      Moravec       725 092 179                 33    Praha
3      Dominika      Kopecká       722 747 626                 34    Praha
4        Marcel        Hájek  +421 902 928 669                 35    Praha
5        Milada    Hernandez       773 373 704                 38    Praha
6     Catherine       Bender       604 068 460                 40    Praha
7          Olga      Němcová  +421 914 172 243                 41    Praha
8       Jeffrey      Šťastný       607 628 821                 44    Praha
9        Kamila       Říhová  +421 948 396 069                 47    Praha
10      Jaromír       Miller  +421 912 615 902                 49    Praha
11  Christopher        Zeman  +421 948 150 084                 51    Praha
12     Karolína        Short       721 589 083                 53    Praha
13     Michelle      Vlčková  +421 41 720 7806                 54    Praha
14      Jeffrey     Pospíšil  +421 55 491 6940                 56    Praha
15     Ladislav       Blažek  +421 910 274 975                 57    Praha
16         John       Bailey       775 021 116                 58    Praha
17      William      Shelton  +421 47 745 8219                 60    Praha
18    Miroslava       Veselá       774 029 254                 62    Praha
19      William    Alexander  +421 949 106 724                 63    Praha
20     Kimberly         Bass  +421 912 169 840                 64    Praha
21       Nathan      Svoboda       728 710 923                 66    Praha
22        Luděk       Bartoš  +421 940 700 326                 69    Praha
23       Dillon        Black       734 300 978                 70    Praha
24       Robert         Říha       727 351 984                 72    Praha
25        Steve        Šimek       604 966 101                 74    Praha
26      Theresa     Kučerová  +421 48 528 0081                 76    Praha
27        Marta       Butler  +421 944 196 827                 78    Praha
28     Samantha    Kadlecová  +421 904 841 543                 80    Praha
29        Stacy  Pospíšilová       727 293 880                  3    Plzeň
30        Matěj         Král       770 787 377                  6    Plzeň
31       Amanda       Wilson  +421 52 656 7231                  7    Plzeň
32        Angel       Wilson  +421 52 135 2491                  8    Plzeň
33     Jindřich       Howell  +421 39 043 0948                 10    Plzeň
34    Alexander     Martinez       721 195 689                 13    Plzeň
35        Radim      Kopecký  +421 917 371 226                 16    Plzeň
36     Miroslav         Reed       774 829 074                 18    Plzeň
37       Emilie       Powell       731 380 539                 21    Plzeň
38       Nikola         Wade       726 763 154                 22    Plzeň
39    Katherine         Reed       726 214 968                 23    Plzeň
40        Kayla     Urbanová       737 772 985                 24    Plzeň
41        Roman       Moreno       722 284 985                 26    Plzeň
42     Bohumila        Smith       608 121 912                 27    Plzeň
43      Blažena        Smith  +421 51 828 2591                 28    Plzeň
44      Phillip         Malý       731 594 560                 29    Plzeň
45         Nela      Šťastná       728 454 176                 83  Liberec
46      Heather      Marková       604 404 522                 84  Liberec
47       Krista  Procházková  +421 50 444 5544                 85  Liberec
48     Jennifer        Brown       775 545 190                 86  Liberec
49    Ladislava    Blackwell  +421 913 487 200                 87  Liberec
50       Robert       Macias  +421 49 929 6856                 88  Liberec
51         Dana        Reyes  +421 904 153 942                 90  Liberec
52        Vasyl       Veselý       603 759 413                 92  Liberec
53        Randy       Veselý       777 149 125                 95  Liberec
54       Audrey        Allen  +421 908 839 506                 96  Liberec
55         Ivan       Bartoš       603 226 051                 99  Liberec

In [42]:
# Ze souboru platy_2021_02.csv načti platy zaměstnanců za únor 2021. Propoj tabulku (operace join) s platy a tabulku se zaměstnanci pomocí sloupce cislo_zamestnance.
# načtení hotovo viz výše

# platy_zamci = pandas.merge(zamci,platy, on = ["cislo_zamestnance"])
platy_zamci = pandas.merge(zamci,platy, on = ["cislo_zamestnance"], how="left")
platy_zamci.shape

(56, 6)

In [43]:
platy.shape

(43, 2)

In [44]:
zamci.shape

(56, 5)

In [45]:
platy_zamci

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat
0,Brian,Hall,+421 949 656 098,30,Praha,33500.0
1,Marta,Kolářová,730 456 163,32,Praha,53000.0
2,John,Moravec,725 092 179,33,Praha,38400.0
3,Dominika,Kopecká,722 747 626,34,Praha,36800.0
4,Marcel,Hájek,+421 902 928 669,35,Praha,NaN
5,Milada,Hernandez,773 373 704,38,Praha,32600.0
6,Catherine,Bender,604 068 460,40,Praha,32800.0
7,Olga,Němcová,+421 914 172 243,41,Praha,49300.0
8,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0
9,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
10,Jaromír,Miller,+421 912 615 902,49,Praha,58400.0
11,Christopher,Zeman,+421 948 150 084,51,Praha,37100.0
12,Karolína,Short,721 589 083,53,Praha,NaN
13,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN
14,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0
15,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0
16,John,Bailey,775 021 116,58,Praha,NaN
17,William,Shelton,+421 47 745 8219,60,Praha,NaN
18,Miroslava,Veselá,774 029 254,62,Praha,NaN
19,William,Alexander,+421 949 106 724,63,Praha,31400.0
20,Kimberly,Bass,+421 912 169 840,64,Praha,36900.0
21,Nathan,Svoboda,728 710 923,66,Praha,NaN
22,Luděk,Bartoš,+421 940 700 326,69,Praha,32600.0
23,Dillon,Black,734 300 978,70,Praha,52600.0
24,Robert,Říha,727 351 984,72,Praha,NaN
25,Steve,Šimek,604 966 101,74,Praha,49300.0
26,Theresa,Kučerová,+421 48 528 0081,76,Praha,55400.0
27,Marta,Butler,+421 944 196 827,78,Praha,52600.0
28,Samantha,Kadlecová,+421 904 841 543,80,Praha,57700.0
29,Stacy,Pospíšilová,727 293 880,3,Plzeň,54900.0
30,Matěj,Král,770 787 377,6,Plzeň,54800.0
31,Amanda,Wilson,+421 52 656 7231,7,Plzeň,36400.0
32,Angel,Wilson,+421 52 135 2491,8,Plzeň,47900.0
33,Jindřich,Howell,+421 39 043 0948,10,Plzeň,NaN
34,Alexander,Martinez,721 195 689,13,Plzeň,NaN
35,Radim,Kopecký,+421 917 371 226,16,Plzeň,34200.0
36,Miroslav,Reed,774 829 074,18,Plzeň,35400.0
37,Emilie,Powell,731 380 539,21,Plzeň,54200.0
38,Nikola,Wade,726 763 154,22,Plzeň,34400.0
39,Katherine,Reed,726 214 968,23,Plzeň,39000.0
40,Kayla,Urbanová,737 772 985,24,Plzeň,44200.0
41,Roman,Moreno,722 284 985,26,Plzeň,59600.0
42,Bohumila,Smith,608 121 912,27,Plzeň,45100.0
43,Blažena,Smith,+421 51 828 2591,28,Plzeň,38100.0
44,Phillip,Malý,731 594 560,29,Plzeň,48900.0
45,Nela,Šťastná,728 454 176,83,Liberec,46500.0
46,Heather,Marková,604 404 522,84,Liberec,38600.0
47,Krista,Procházková,+421 50 444 5544,85,Liberec,44200.0
48,Jennifer,Brown,775 545 190,86,Liberec,NaN
49,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0
50,Robert,Macias,+421 49 929 6856,88,Liberec,NaN
51,Dana,Reyes,+421 904 153 942,90,Liberec,41100.0
52,Vasyl,Veselý,603 759 413,92,Liberec,48100.0
53,Randy,Veselý,777 149 125,95,Liberec,31600.0
54,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0
55,Ivan,Bartoš,603 226 051,99,Liberec,NaN

In [46]:
platy_mesto_prum = platy_zamci.groupby("mesto")[["plat"]].mean()
platy_mesto_prum

                 plat
mesto
Liberec  43775.000000
Plzeň    44792.857143
Praha    43295.238095

### Dobrovolný doplněk

In [64]:
# Ulož do proměnné počet zaměstnaců, kteří v naší firmě již nepracují.

pocet_neprac = platy_zamci["plat"].isnull().sum()
pocet_neprac

# nebo
pocet_neprac = platy_zamci[platy_zamci["plat"].isnull()].shape[0]
pocet_neprac

13

In [116]:
# všechny sloupce, které jsou problematické a obsahují null
platy_zamci.isnull().sum()

jmeno                 0
prijimeni             0
telefonni_cislo       0
cislo_zamestnance     0
mesto                 0
plat                 13
je_zamec?             0
je_zamec              0
dtype: int64

In [76]:
# V rámci úspory se IT oddělení rozhodlo prověřit licence přidělené zaměstnancům, kteří ve firmě již nepracují. Vytvoř samostatnou tabulku, která obsahuje jména zaměstnanců, 
# kteří ve firmě již nepracují. Tabulku ulož do souboru CSV.

# platy_zamci["plat"].isnull()

import numpy

platy_zamci["je_zamec"] = numpy.where(platy_zamci["plat"].isnull(),"Ne","Ano")
platy_zamci

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat,je_zamec?,je_zamec
0,Brian,Hall,+421 949 656 098,30,Praha,33500.0,Ano,Ano
1,Marta,Kolářová,730 456 163,32,Praha,53000.0,Ano,Ano
2,John,Moravec,725 092 179,33,Praha,38400.0,Ano,Ano
3,Dominika,Kopecká,722 747 626,34,Praha,36800.0,Ano,Ano
4,Marcel,Hájek,+421 902 928 669,35,Praha,NaN,Ne,Ne
5,Milada,Hernandez,773 373 704,38,Praha,32600.0,Ano,Ano
6,Catherine,Bender,604 068 460,40,Praha,32800.0,Ano,Ano
7,Olga,Němcová,+421 914 172 243,41,Praha,49300.0,Ano,Ano
8,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0,Ano,Ano
9,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0,Ano,Ano
10,Jaromír,Miller,+421 912 615 902,49,Praha,58400.0,Ano,Ano
11,Christopher,Zeman,+421 948 150 084,51,Praha,37100.0,Ano,Ano
12,Karolína,Short,721 589 083,53,Praha,NaN,Ne,Ne
13,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN,Ne,Ne
14,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0,Ano,Ano
15,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0,Ano,Ano
16,John,Bailey,775 021 116,58,Praha,NaN,Ne,Ne
17,William,Shelton,+421 47 745 8219,60,Praha,NaN,Ne,Ne
18,Miroslava,Veselá,774 029 254,62,Praha,NaN,Ne,Ne
19,William,Alexander,+421 949 106 724,63,Praha,31400.0,Ano,Ano
20,Kimberly,Bass,+421 912 169 840,64,Praha,36900.0,Ano,Ano
21,Nathan,Svoboda,728 710 923,66,Praha,NaN,Ne,Ne
22,Luděk,Bartoš,+421 940 700 326,69,Praha,32600.0,Ano,Ano
23,Dillon,Black,734 300 978,70,Praha,52600.0,Ano,Ano
24,Robert,Říha,727 351 984,72,Praha,NaN,Ne,Ne
25,Steve,Šimek,604 966 101,74,Praha,49300.0,Ano,Ano
26,Theresa,Kučerová,+421 48 528 0081,76,Praha,55400.0,Ano,Ano
27,Marta,Butler,+421 944 196 827,78,Praha,52600.0,Ano,Ano
28,Samantha,Kadlecová,+421 904 841 543,80,Praha,57700.0,Ano,Ano
29,Stacy,Pospíšilová,727 293 880,3,Plzeň,54900.0,Ano,Ano
30,Matěj,Král,770 787 377,6,Plzeň,54800.0,Ano,Ano
31,Amanda,Wilson,+421 52 656 7231,7,Plzeň,36400.0,Ano,Ano
32,Angel,Wilson,+421 52 135 2491,8,Plzeň,47900.0,Ano,Ano
33,Jindřich,Howell,+421 39 043 0948,10,Plzeň,NaN,Ne,Ne
34,Alexander,Martinez,721 195 689,13,Plzeň,NaN,Ne,Ne
35,Radim,Kopecký,+421 917 371 226,16,Plzeň,34200.0,Ano,Ano
36,Miroslav,Reed,774 829 074,18,Plzeň,35400.0,Ano,Ano
37,Emilie,Powell,731 380 539,21,Plzeň,54200.0,Ano,Ano
38,Nikola,Wade,726 763 154,22,Plzeň,34400.0,Ano,Ano
39,Katherine,Reed,726 214 968,23,Plzeň,39000.0,Ano,Ano
40,Kayla,Urbanová,737 772 985,24,Plzeň,44200.0,Ano,Ano
41,Roman,Moreno,722 284 985,26,Plzeň,59600.0,Ano,Ano
42,Bohumila,Smith,608 121 912,27,Plzeň,45100.0,Ano,Ano
43,Blažena,Smith,+421 51 828 2591,28,Plzeň,38100.0,Ano,Ano
44,Phillip,Malý,731 594 560,29,Plzeň,48900.0,Ano,Ano
45,Nela,Šťastná,728 454 176,83,Liberec,46500.0,Ano,Ano
46,Heather,Marková,604 404 522,84,Liberec,38600.0,Ano,Ano
47,Krista,Procházková,+421 50 444 5544,85,Liberec,44200.0,Ano,Ano
48,Jennifer,Brown,775 545 190,86,Liberec,NaN,Ne,Ne
49,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0,Ano,Ano
50,Robert,Macias,+421 49 929 6856,88,Liberec,NaN,Ne,Ne
51,Dana,Reyes,+421 904 153 942,90,Liberec,41100.0,Ano,Ano
52,Vasyl,Veselý,603 759 413,92,Liberec,48100.0,Ano,Ano
53,Randy,Veselý,777 149 125,95,Liberec,31600.0,Ano,Ano
54,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0,Ano,Ano
55,Ivan,Bartoš,603 226 051,99,Liberec,NaN,Ne,Ne

In [118]:
nezamci = platy_zamci.query("je_zamec == 'Ne'")
nezamci

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat,je_zamec?,je_zamec
4,Marcel,Hájek,+421 902 928 669,35,Praha,NaN,Ne,Ne
12,Karolína,Short,721 589 083,53,Praha,NaN,Ne,Ne
13,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN,Ne,Ne
16,John,Bailey,775 021 116,58,Praha,NaN,Ne,Ne
17,William,Shelton,+421 47 745 8219,60,Praha,NaN,Ne,Ne
18,Miroslava,Veselá,774 029 254,62,Praha,NaN,Ne,Ne
21,Nathan,Svoboda,728 710 923,66,Praha,NaN,Ne,Ne
24,Robert,Říha,727 351 984,72,Praha,NaN,Ne,Ne
33,Jindřich,Howell,+421 39 043 0948,10,Plzeň,NaN,Ne,Ne
34,Alexander,Martinez,721 195 689,13,Plzeň,NaN,Ne,Ne
48,Jennifer,Brown,775 545 190,86,Liberec,NaN,Ne,Ne
50,Robert,Macias,+421 49 929 6856,88,Liberec,NaN,Ne,Ne
55,Ivan,Bartoš,603 226 051,99,Liberec,NaN,Ne,Ne

In [97]:
nezamci.sort_index().to_csv("ukol-10_nezamci.csv", mode="w", index = False)

# Projekty

Pokračuj ve své práci pro softwarovou firmu. Ze souboru vykazy.csv načti informace o výkazech na projekty pro jednoho vybraného zákazníka.

import requests

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/vykazy.csv")

open("vykazy.csv", "wb").write(r.content)

Načti data ze souboru a ulož je do tabulky.

Proveď agregaci a zjisti celkový počet vykázaných hodin za jednotlivé projekty.

### Dobrovolný doplněk

Propoj tabulku s výkazy s tabulkou se zaměstnanci, kterou jsi vytvořil(a) v předchozím cvičení.

Následně proveď statistiku vykázaných hodin za jednotlivé kanceláře, tj. spočítej celkový počet hodin vykázaný zaměstnanci jednotlivých kanceláří na projekty daného zákazníka.

In [91]:
# import requests

r = requests.get("https://raw.githubusercontent.com/andywaltlova/python-1-podzim-2022/master/ukoly/data/vykazy.csv")
open("ukol-10_vykazy.csv", "wb").write(r.content)

623

In [92]:
# import pandas

vykazy = pandas.read_csv("ukol-10_vykazy.csv") 
vykazy

          date  hours project  emloyee_id
0   2021-02-01    2.5     F30          13
1   2021-02-01    3.4     W05          70
2   2021-02-01    2.1     JL9          72
3   2021-02-01    5.2     F30           3
4   2021-02-01    2.4     TE1          54
5   2021-02-01    4.1     TE1          83
6   2021-02-01    5.4     W05          92
7   2021-02-01    2.2     YLI          34
8   2021-02-01    2.7     YLI          84
9   2021-02-01    4.4     W05          30
10  2021-02-02    5.6     F30          53
11  2021-02-02    2.6     W05          47
12  2021-02-02    2.4     YLI          44
13  2021-02-02    3.1     YLI          40
14  2021-02-02    5.3     YLI          10
15  2021-02-02    3.6     YLI          53
16  2021-02-02    5.6     F30          56
17  2021-02-03    4.0     W05          53
18  2021-02-03    4.6     TE1          86
19  2021-02-03    2.6     F30          18
20  2021-02-03    2.8     TE1          47
21  2021-02-03    2.6     YLI          34
22  2021-02-03    3.7     YLI          96
23  2021-02-03    5.2     W05          57
24  2021-02-03    5.5     W05          40
25  2021-02-03    5.4     YLI          86
26  2021-02-03    2.1     TE1          87

In [95]:
# Proveď agregaci a zjisti celkový počet vykázaných hodin za jednotlivé projekty.

vykazy.groupby("project")[["project","hours"]].sum()

C:\Users\zitko\AppData\Local\Temp\ipykernel_33944\1581525646.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  vykazy.groupby("project")[["project","hours"]].sum()

         hours
project
F30       21.5
JL9        2.1
TE1       16.0
W05       30.5
YLI       31.0

In [105]:
# Propoj tabulku s výkazy s tabulkou se zaměstnanci, kterou jsi vytvořil(a) v předchozím cvičení.

# přejmenování sloupce z emloyee_id na employee_id
vykazy = vykazy.rename(columns={"emloyee_id":"employee_id"})

In [119]:
# spojení dvou dataframe s jiným názvem klíčových sloupců (obsahují ale identický klíč)
zamci_hod_vykazy = pandas.merge(zamci, vykazy, left_on = "cislo_zamestnance", right_on = "employee_id")¨


# Kdyz vybiras jen nejake sloupce, musis vzdy vybrat ty, pres ktere to spojujes (a jakekoliv dalsi k tomu). Zde ten spojovací je employee_id, které mi chybělo
zamci_hod_vykazy = pandas.merge(zamci[["jmeno","prijimeni","cislo_zamestnance", "mesto"]], vykazy[["hours","project", "employee_id"]], left_on = "cislo_zamestnance", right_on = "employee_id")
zamci_hod_vykazy

,jmeno,prijimeni,cislo_zamestnance,mesto,hours,project,employee_id
0,Brian,Hall,30,Praha,4.4,W05,30
1,Dominika,Kopecká,34,Praha,2.2,YLI,34
2,Dominika,Kopecká,34,Praha,2.6,YLI,34
3,Catherine,Bender,40,Praha,3.1,YLI,40
4,Catherine,Bender,40,Praha,5.5,W05,40
5,Jeffrey,Šťastný,44,Praha,2.4,YLI,44
6,Kamila,Říhová,47,Praha,2.6,W05,47
7,Kamila,Říhová,47,Praha,2.8,TE1,47
8,Karolína,Short,53,Praha,5.6,F30,53
9,Karolína,Short,53,Praha,3.6,YLI,53
10,Karolína,Short,53,Praha,4.0,W05,53
11,Michelle,Vlčková,54,Praha,2.4,TE1,54
12,Jeffrey,Pospíšil,56,Praha,5.6,F30,56
13,Ladislav,Blažek,57,Praha,5.2,W05,57
14,Dillon,Black,70,Praha,3.4,W05,70
15,Robert,Říha,72,Praha,2.1,JL9,72
16,Stacy,Pospíšilová,3,Plzeň,5.2,F30,3
17,Jindřich,Howell,10,Plzeň,5.3,YLI,10
18,Alexander,Martinez,13,Plzeň,2.5,F30,13
19,Miroslav,Reed,18,Plzeň,2.6,F30,18
20,Nela,Šťastná,83,Liberec,4.1,TE1,83
21,Heather,Marková,84,Liberec,2.7,YLI,84
22,Jennifer,Brown,86,Liberec,4.6,TE1,86
23,Jennifer,Brown,86,Liberec,5.4,YLI,86
24,Ladislava,Blackwell,87,Liberec,2.1,TE1,87
25,Vasyl,Veselý,92,Liberec,5.4,W05,92
26,Audrey,Allen,96,Liberec,3.7,YLI,96

In [115]:
# Následně proveď statistiku vykázaných hodin za jednotlivé kanceláře, tj. spočítej celkový počet hodin vykázaný zaměstnanci jednotlivých kanceláří na projekty daného zákazníka.

zamci_hod_vykazy.groupby(["mesto","project"])[["hours"]].sum()

# nebo
zamci_hod_vykazy.groupby(["mesto","project"]).agg({"hours":["sum"]})

                hours
                  sum
mesto   project
Liberec TE1      10.8
        W05       5.4
        YLI      11.8
Plzeň   F30      10.3
        YLI       5.3
Praha   F30      11.2
        JL9       2.1
        TE1       5.2
        W05      25.1
        YLI      13.9